Repository vi-wolhwa/github-pr-manager, pull requests merged in 2025-06, with the labels that each got.

#16 [05/24] [디자인 시스템 적용] feat: @primer/react 세팅 popup 테스트
  .yarn/install-state.gz
  package.json
  src/pages/popup/Popup/Popup.module.scss
  src/pages/popup/Popup/components/UserCode/index.tsx
  src/pages/popup/Popup/index.tsx
  src/pages/popup/index.tsx
  yarn.lock
Labels: 🛠 환경설정

#18 [05/24] [PR Template] feat: PR template 깃허브 API 불러오기
  src/constants/apiURL.ts
  src/pages/content/PRTemplates/apis/fetchPRTemplates.ts
  src/pages/content/PRTemplates/components/InsertPRTemplates/index.tsx
  src/pages/content/PRTemplates/constants/selector.ts
  src/pages/content/PRTemplates/helpers/getRepoPath.ts
  src/pages/content/PRTemplates/index.tsx
  src/pages/content/shared/constants/pageUrls.ts
  src/pages/content/shared/utils/siteUtils.ts
Labels: ✨ 기능추가

#23 [06/07] [팝업 탭] feat: 팝업 탭
  .eslintrc
  .yarn/install-state.gz
  package.json
  src/pages/popup/Popup/components/Button/Button.module.scss
  src/pages/popup/Popup/components/Button/index.tsx
  src/pages/popup/Popup/components/PRTemplateSetting/TemplateInput/TemplateInput.module.scss
  src/pages/popup/Popup/components/PRTitles/ServiceList/ServiceList.module.scss
  src/pages/popup/Popup/components/PRTitles/ServiceList/index.tsx
  src/pages/popup/Popup/components/PRTitles/TemplateInput/TemplateInput.module.scss
  src/pages/popup/Popup/components/PRTitles/TemplateInput/index.tsx
  src/pages/popup/Popup/components/PRTitles/Wrapper/Wrapper.module.scss
  src/pages/popup/Popup/components/PRTitles/Wrapper/index.tsx
  src/pages/popup/Popup/components/PRTitles/index.tsx
  src/pages/popup/Popup/components/PanelWrapper/PanelWrapper.module.scss
  src/pages/popup/Popup/components/PanelWrapper/index.tsx
  src/pages/popup/Popup/constants/tabs.ts
  src/pages/popup/Popup/containers/Home/index.tsx
  src/pages/popup/Popup/containers/PRTemplate/index.tsx
  src/pages/popup/Popup/containers/PRTitleAutoInsert/index.tsx
  src/pages/popup/Popup/containers/Settings/index.tsx
  src/pages/popup/Popup/index.tsx
  tsconfig.json
  utils/reload/initReloadServer.ts
  yarn.lock
Labels: ✨ 기능추가

#25 [PR 제목 자동 삽입] fix: PR setInterval -> observer 방식으로 전환
  src/pages/content/prTitleAutoInsert/index.tsx
Labels: 🔨 리팩토링

#28 [06/09] [pr_title_build] fix: 빌드에러 해결
  src/pages/content/prTitleAutoInsert/index.tsx
Labels: 🐛 버그수정

#30 [06/09] [pr_title] refactor: setInterval 로직 삭제
  .yarn/install-state.gz
  src/pages/content/prTitleAutoInsert/index.tsx
  yarn.lock
Labels: 🔨 리팩토링

#31 [Popup] feat: 팝업 ui 및 설명
  src/pages/popup/Popup/components/LabelBox/index.tsx
  src/pages/popup/Popup/constants/index.ts
  src/pages/popup/Popup/constants/tabs.ts
  src/pages/popup/Popup/containers/Home/index.tsx
  src/pages/popup/Popup/containers/Settings/index.tsx
  src/pages/popup/Popup/index.tsx
Labels: ✨ 기능추가

#33 [Setting] fix: PR 템플릿 동기화 버튼 연결
  src/pages/content/PRTemplates/apis/fetchPRTemplates.ts
  src/pages/popup/Popup/containers/PRTemplate/index.tsx
  src/pages/popup/Popup/containers/Settings/index.tsx
  src/pages/popup/Popup/index.tsx
Labels: ✨ 기능추가
